### ISSUE TITLE
CSS file of 320 bytes takes 10+ seconds to parse

### ISSUE THREAD

**Issue by vdmit** [jaraco/cssutils#18]
I've encountered CSS file which `cssutils` library takes lots of seconds to parse (in fact, almost infinite).
After some investigation I've minified problematic sample (as possible) and prepared reproducible code example.
On my laptop (core i7-8550U) it takes **14 seconds** to parse file with just one line and 320 bytes of text.

Original file has 20kBytes of text and parser does not finish it in several hours.

Code: 
https://gist.github.com/vdmit/ef9007170fa1c616cf5aba1fcebfce87
I'm using:
- latest stable `cssutils` release 2.3.0 from pypi repo
- python 3.8.10
- Ubuntu 20.04 linux distribution.

Notes:
- original CSS file was malformed and even contained non-printable characters. My minified example is still not valid CSS file, but it is a plain ANSI file.
- Adding line break in any place fixes problem;
- Removing of last style expression (`.s11...` reduces execution time from 14 seconds to 3 seconds). 

Traceback of interrupted script is following:

```python3 cssutils_infinite_loop_bug_example.py
Traceback (most recent call last):
  File "cssutils_infinite_loop_bug_example.py", line 10, in <module>
    sheet = css_parser.parseString(cssText=css_text)
  File "/home/vdmit/.local/lib/python3.8/site-packages/cssutils/parse.py", line 147, in parseString
    sheet._setCssTextWithEncodingOverride(
  File "/home/vdmit/.local/lib/python3.8/site-packages/cssutils/css/cssstylesheet.py", line 408, in _setCssTextWithEncodingOverride
    self.cssText = cssText
  File "/home/vdmit/.local/lib/python3.8/site-packages/cssutils/css/cssstylesheet.py", line 331, in _setCssText
    wellformed, expected = self._parse(
  File "/home/vdmit/.local/lib/python3.8/site-packages/cssutils/util.py", line 484, in _parse
    expected = p(expected, seq, token, tokenizer)
  File "/home/vdmit/.local/lib/python3.8/site-packages/cssutils/css/cssstylesheet.py", line 313, in ruleset
    rule.cssText = self._tokensupto2(tokenizer, token)
  File "/home/vdmit/.local/lib/python3.8/site-packages/cssutils/util.py", line 343, in _tokensupto2
    for token in tokenizer:
  File "/home/vdmit/.local/lib/python3.8/site-packages/cssutils/tokenize2.py", line 172, in tokenize
    match = matcher(text, pos)  # if no match try next production
KeyboardInterrupt
```

**Comment by jaraco** [comment]
Thanks for the report.

I welcome investigation or a patch.

**Comment by InconceivableVizzini** [comment]
No patch at the moment, but I believe this is related to backtracking in the regular expressions parsing strings, for the specific input shared. The lengthy call is located at https://github.com/jaraco/cssutils/blob/d9d2bdcc62cd21f7ee5e778af4853ecd2cf8d7d9/cssutils/tokenize2.py#L172

When the input is `'` and the matcher is related to the string production,

https://github.com/jaraco/cssutils/blob/d9d2bdcc62cd21f7ee5e778af4853ecd2cf8d7d9/cssutils/cssproductions.py#L32

**Comment by InconceivableVizzini** [comment]
This can be fixed by rewriting the string productions (`r"'(\\.|[^'])*'"`) or using an alternative regular expression library that does not rely on backtracking, such as [re2](https://pypi.org/project/re2/), which may be used as a drop-in replacement of `re`.

**Comment by jaraco** [comment]
> This can be fixed by rewriting the string productions (`r"'(\\.|[^'])*'"`) or using an alternative regular expression library that does not rely on backtracking, such as [re2](https://pypi.org/project/re2/), which may be used as a drop-in replacement of `re`.

I'd prefer to see a rewrite of the string productions, especially if it can be done in a fairly straightforward way and without adding to much complication to the approach.
